---
- name: Install Shadowsocks dependencies
  apt: pkg={{ item }}
  with_items:
    - "{{ shadowsocks_dependencies }}"

- name: Add the Shadowsocks user
  user: name=shadowsocks
        home={{ shadowsocks_location }}
        shell=/usr/sbin/nologin
        comment="Shadowsocks User"

- name: Generate a random Shadowsocks password
  shell: openssl rand -base64 24 > {{ shadowsocks_password_file }}
         creates={{ shadowsocks_password_file }}

- name: Register Shadowsocks password
  command: cat {{ shadowsocks_password_file }}
  register: shadowsocks_password

- name: Install Shadowsocks
  pip: name=shadowsocks

- name: Generate Shadowsocks config file
  template: src=config.json.j2
            dest={{ shadowsocks_location }}/config.json
            owner=shadowsocks
            group=shadowsocks
            mode=640
  notify: Restart Shadowsocks

- name: Generate Shadowsocks init script
  template: src=shadowsocks-init.j2
            dest=/etc/init.d/shadowsocks
            owner=root
            group=root
            mode=755

- name: Enable the Shadowsocks init script so the service will start at boot
  command: update-rc.d shadowsocks defaults
           creates=/etc/rc0.d/K01shadowsocks

- name: Set permissions on the Shadowsocks password file
  file: path={{ item }}
        owner=shadowsocks
        group=shadowsocks
        mode=640
  with_items:
    - "{{ shadowsocks_password_file }}"

- name: Pause for explanation
  pause: prompt="Your randomly chosen Shadowsocks password is '{{ shadowsocks_password.stdout }}'. Press any key to continue..."
